FROM python:3.7.3
LABEL Description="Metrics Collector" Vendor="Maiara Coelho" Version="1.0"

EXPOSE 9191

WORKDIR /usr/src/api

COPY requirements /usr/src/api

RUN pip install -r /usr/src/api/requirements

#RUN rm requirements




